<?php
$flashMessage = $this->flashMessenger()->getMessages();

if (count($flashMessage)) :
?>
    <?php
        foreach ($flashMessage as $msg) :
            foreach ($msg as $type => $message) :
                ?>
                <div class="alert alert-info"><?php echo $message; ?></div>
            <?php endforeach; ?>
        <?php endforeach; ?>
    <?php endif; ?>
    <?php if(isset($this->messages)) : ?>
        <?php foreach ($this->messages as $type => $msg) : ?>
            <div class="alert alert-info"><?php echo $msg; ?></div>
        <?php endforeach; ?>

<?php endif; ?>
<div class="row" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <div class="col-md-6 ">
        <img src="img/logo.png" style="padding: 20px 10px 20px 25%;"/>
        <?php
        $form = $this->loginForm;
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <div class="form-group">
            <label for="exampleInputEmail1">Usuario</label>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
                <?php echo $this->formElement($form->get('email')); ?>
            </div>
            <?php if($this->formElementErrors($form->get('email')) != null) : ?>
                <div class="alert alert-danger" role="alert">
                    <?php echo $this->formElementErrors($form->get('email'));?>
                </div>
            <?php endif; ?>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Contraseña</label>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></span>
                <?php echo $this->formElement($form->get('password')); ?>
            </div>
            <?php if($this->formElementErrors($form->get('password')) != null) : ?>
                <div class="alert alert-danger" role="alert">
                    <?php echo $this->formElementErrors($form->get('password'));?>
                </div>
            <?php endif ?>
        </div>
        <button type="submit" class="btn btn-default"> <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&emsp; Iniciar seccion</button>
        <?php
        echo $this->formRow($form->get('loginCsrf'));
        ?>
        </td>
        <?php
        echo $this->form()->closeTag($form);
        ?>
    </div>
    <div class="col-md-6 hidden-xs">
        <h3>Registro de Stock IT</h3>
        <p class="text-justify">
            Esta herramienta tiene la capacidad de poder llevar y controlar el registro de los activos en almacén de los medios IT(Information technology).
            </br></br>
            Esta aplicación desarrollada en las más novedosas aplicaciones basadas en web capaz de llegar a todos los dispositivos tanto como Desktop, Tablet y Móviles se realizó con el objetivo de poder llevar un mejor inventario de los equipos que hay en almacén de los medios de computo llevando un KARDEX(Registro) de las entradas y salidas del almacén.
            </br></br>
            También cuenta con un registro de proveedores y categorías de productos para su clasificación y poder llevar un mejor control de los productos.
            </br></br>
            Este sistema web se puede implementar en pequeñas empresas, y en talleres de reparaciones de cómputo y de móviles para llevar el control de las piezas de repuestos y sus proveedores
        </p>
    </div>
</div>
<div class="clearfix"></div>