<?php
$form = $this->proveedorForm;
$form->setAttribute('action', $this->url('addproveedor'));
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Añadir Proveedor</h4>
    </div>
    <div class="modal-body">
        <div class="panel-default">
            <div class="panel-body table-responsive">
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>RUC</label>
                            <?php echo $this->formElement($form->get('ruc')); ?>
                            <?php if($this->formElementErrors($form->get('ruc')) != null) : ?>
                                <div class="alert alert-danger" role="alert">
                                    <?php echo $this->formElementErrors($form->get('ruc'));?>
                                </div>
                            <?php endif; ?>
                        </div>

                        <div class="form-group">
                            <label>Razon Social</label>
                            <?php echo $this->formElement($form->get('razon_social')); ?>
                            <?php if($this->formElementErrors($form->get('razon_social')) != null) : ?>
                                <div class="alert alert-danger" role="alert">
                                    <?php echo $this->formElementErrors($form->get('razon_social'));?>
                                </div>
                            <?php endif; ?>
                        </div>

                        <div class="form-group">
                            <label>Nombre</label>
                            <?php echo $this->formElement($form->get('nombre')); ?>
                            <?php if($this->formElementErrors($form->get('nombre')) != null) : ?>
                                <div class="alert alert-danger" role="alert">
                                    <?php echo $this->formElementErrors($form->get('nombre'));?>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="form-group">
                            <label>Direccion</label>
                            <?php echo $this->formElement($form->get('direccion')); ?>
                            <?php if($this->formElementErrors($form->get('direccion')) != null) : ?>
                                <div class="alert alert-danger" role="alert">
                                    <?php echo $this->formElementErrors($form->get('direccion'));?>
                                </div>
                            <?php endif; ?>
                        </div>

                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Telefono</label>
                            <?php echo $this->formElement($form->get('telefono')); ?>
                            <?php if($this->formElementErrors($form->get('telefono')) != null) : ?>
                                <div class="alert alert-danger" role="alert">
                                    <?php echo $this->formElementErrors($form->get('telefono'));?>
                                </div>
                            <?php endif; ?>
                        </div>

                        <div class="form-group">
                            <label>Celular</label>
                            <?php echo $this->formElement($form->get('celular')); ?>
                            <?php if($this->formElementErrors($form->get('celular')) != null) : ?>
                                <div class="alert alert-danger" role="alert">
                                    <?php echo $this->formElementErrors($form->get('celular'));?>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <?php echo $this->formElement($form->get('email')); ?>
                            <?php if($this->formElementErrors($form->get('email')) != null) : ?>
                                <div class="alert alert-danger" role="alert">
                                    <?php echo $this->formElementErrors($form->get('email'));?>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="form-group">
                            <label>Ciudad</label>
                            <?php echo $this->formElement($form->get('ciudad')); ?>
                            <?php if($this->formElementErrors($form->get('ciudad')) != null) : ?>
                                <div class="alert alert-danger" role="alert">
                                    <?php echo $this->formElementErrors($form->get('ciudad'));?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label>Sitio web</label>
                    <?php echo $this->formElement($form->get('url')); ?>
                    <?php if($this->formElementErrors($form->get('url')) != null) : ?>
                        <div class="alert alert-danger" role="alert">
                            <?php echo $this->formElementErrors($form->get('url'));?>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="form-group">
                    <label>Observacion</label>
                    <?php echo $this->formElement($form->get('observacion')); ?>
                    <?php if($this->formElementErrors($form->get('observacion')) != null) : ?>
                        <div class="alert alert-danger" role="alert">
                            <?php echo $this->formElementErrors($form->get('observacion'));?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <?php echo $this->formElement($form->get('reset')); ?>
        <?php echo $this->formElement($form->get('submit')); ?>
    </div>
<?php
echo $this->form()->closeTag($form);
?>
    <script>
        $(document).ready(function(){

            $('#myModal').on('shown.bs.modal', function () {
                $('#myInput').focus()
            });

            $("#proveedorForm").submit(function (e) {
                e.preventDefault();
                $( "#result"  ).hide();
                var parametros = {
                    ruc : $(this).find( "input[name='ruc']" ).val(),
                    razon_social : $(this).find( "input[name='razon_social']" ).val(),
                    nombre : $(this).find( "input[name='nombre']" ).val(),
                    direccion : $(this).find( "input[name='direccion']" ).val(),
                    telefono : $(this).find( "input[name='telefono']" ).val(),
                    celular : $(this).find( "input[name='celular']" ).val(),
                    email : $(this).find( "input[name='email']" ).val(),
                    ciudad : $(this).find( "input[name='ciudad']" ).val(),
                    url : $(this).find( "input[name='url']" ).val(),
                    observacion : $(this).find( "input[name='observacion']" ).val(),
                };
                var url = '<?php echo $this->url('addproveedor'); ?>';
                $( "#loading").show();
                var request = $.ajax({
                    url:  url,
                    type: "POST",
                    data: parametros,
                    dataType: "html"
                });

                request.done(function( msg ) {
                    $( "#result" ).html( msg );
                    $( "#result" ).show();
                    $( "#loading" ).hide();
                });
            });
        });
    </script>
