<?php
$flashMessage = $this->flashMessenger()->getMessages();
if (count($flashMessage)) :
?>
<?php
foreach ($flashMessage as $msg) :
    foreach ($msg as $type => $message) :
        ?>
        <div class="alert alert-info"><?php echo $message; ?></div>
    <?php endforeach; ?>
<?php endforeach; ?>
<?php endif; ?>
<?php if(isset($this->messages)) : ?>
    <?php foreach ($this->messages as $type => $msg) : ?>
        <div class="alert alert-info"><?php echo $msg; ?></div>
    <?php endforeach; ?>
<?php endif; ?>
<script>
    $(document).ready(function(){

        $("#passwordForm").submit(function (e) {
            e.preventDefault();
            $( "#result"  ).hide();
            var parametros = {
                password : $(this).find( "input[name='password']" ).val(),
                password_repeat : $(this).find( "input[name='password_repeat']" ).val(),
            };
            var target = $(this).attr("action");
            var url = '<?php echo $this->url('changerpassword')?>';
            $( "#loading").show();
            var request = $.ajax({
                url:  url,
                type: "POST",
                data: parametros,
                dataType: "html"
            });

            request.done(function( msg ) {
                $( "#result" ).html( msg );
                $( "#result" ).show();
                $( "#loading" ).hide();
                //window.location.replace("<?php echo $this->url('perfil')?>")

            });
        });
    });
</script>
<?php
$form = $this->passwordForm;
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="form-group">
    <label>Contraseña</label>
    <?php echo $this->formElement($form->get('password')); ?>
    <?php if($this->formElementErrors($form->get('password')) != null) : ?>
        <div class="alert alert-danger" role="alert">
            <?php echo $this->formElementErrors($form->get('password'));?>
        </div>
    <?php endif; ?>
</div>
<div class="form-group">
    <label>Repetir contraseña</label>
    <?php echo $this->formElement($form->get('password_repeat')); ?>
    <?php if($this->formElementErrors($form->get('password_repeat')) != null) : ?>
        <div class="alert alert-danger" role="alert">
            <?php echo $this->formElementErrors($form->get('password_repeat'));?>
        </div>
    <?php endif; ?>
</div>
<div style="float: right">
    <button class="btn btn-default " type="submit">
        <span class="glyphicon glyphicon-save"></span> Guardar
    </button>
</div>
<?php
echo $this->form()->closeTag($form);
?>
