<?php
$i = 1;
echo $this->headTitle('Inventario Principal');
?>
<?php
echo  $this->headLink()->prependStylesheet($this->basePath() . '/js/datatable/datatables.min.css');
echo $this->headScript()
    ->prependFile($this->basePath() . '/js/datatable/datatables.min.js');
?>
<script>
    $(document).ready(function(){
        $('#myTable').DataTable( {
            autoFill: true
        } );
    });
</script>
<div style="float: right">
    <a href="<?php echo $this->url('invprincipal') ?>">
        <button class="btn btn-default hidden-xs">
            <span class="glyphicon glyphicon-refresh"></span> Actualizar
        </button>
        <button class="btn btn-default visible-xs-inline">
            <span class="glyphicon glyphicon-refresh"></span>
        </button>
    </a>
</div>
<div style="float: right">
    <a href="<?php echo $this->url('addarticulo'); ?>">
    <button class="btn btn-default hidden-xs" data-toggle="modal" data-target="#myModal">
        <span class="glyphicon glyphicon-plus"></span> Añadir Articulo
    </button>
    <button class="btn btn-default visible-xs-inline" data-toggle="modal" data-target="#myModal">
        <span class="glyphicon glyphicon-plus"></span>
    </button>
    </a>
</div>
<div style="float: right">
    <a href="#">
    <button class="btn btn-default hidden-xs" data-toggle="modal" data-target="#myModal">
        <span class="glyphicon glyphicon-save"></span> Reporte PDF
    </button>
    <button class="btn btn-default visible-xs-inline" data-toggle="modal" data-target="#myModal">
        <span class="glyphicon glyphicon-save"></span>
    </button>
    </a>
</div>
<div style="float: right">
    <a href="<?php echo $this->url('rptinventarioxls'); ?>">
    <button class="btn btn-default hidden-xs" data-toggle="modal" data-target="#myModal">
        <span class="glyphicon glyphicon-save"></span> Reporte Excel
    </button>
    <button class="btn btn-default visible-xs-inline" data-toggle="modal" data-target="#myModal">
        <span class="glyphicon glyphicon-save"></span>
    </button>
    </a>
</div>
<h1 class="page-header"><span class="glyphicon glyphicon-align-justify"></span> Inventario Principal</h1>
<div class="panel-info">
    <div class="panel-heading">
        INVENTARIO PRINCIPAL
    </div>
    <div class="panel-body table-responsive">
        <table id="myTable" class="table table-bordered">
            <thead>
            <th class="col-md-1 text-center">OPCIONES</th>
            <th class="col-md-1 text-center">#</th>
            <th class="text-center">CODIGO DE BARRA</th>
            <th class="text-center">PRODUCTOS</th>
            <th class="text-center">MARCA</th>
            <th class="text-center">PRECIO</th>
            <th class="text-center">STOCK</th>
            <th class="text-center">FECHA DE ENTRADA</th>
            <th class="text-center">CATEGORIA</th>
            <th class="text-center">PROVEEDOR</th>
            </thead>
            <tbody>
            <?php foreach ($this->inventario as $inventario) :?>
            <tr>
                <td class="text-center">
                    <a href="<?php echo $this->url('editarticulo'); ?>id/<?php echo $inventario['id_inventario']; ?>" title="Editar">
                        <button class="btn btn-default btn-xs">
                            <span class="glyphicon glyphicon-edit" ></span>
                        </button>
                    </a>
                    <a href="<?php echo $this->url('addarticulostock'); ?>id/<?php echo $inventario['id_inventario']; ?>">
                        <button class="btn btn-default btn-xs" title="Ingresar">
                            <span class="glyphicon glyphicon-plus"></span>
                        </button>
                    </a>
                    <a href="<?php echo $this->url('kardex'); ?>id/<?php echo $inventario['id_inventario']; ?>">
                        <button class="btn btn-default btn-xs" title="Kardex">
                            <span class="glyphicon glyphicon-link"></span>
                        </button>
                    </a>
                    <a href="<?php echo $this->url('salidastock'); ?>id/<?php echo $inventario['id_inventario']; ?>">
                        <button class="btn btn-default btn-xs" title="Salida">
                            <span class="glyphicon glyphicon-minus"></span>
                        </button>
                    </a>
                </td>
                <td class="col-md-1 text-center"><?php echo $i; ?></td>
                <td class="text-center"><?php echo $inventario['codigo']; ?></td>
                <td class="text-center"><?php echo $inventario['productos']; ?></td>
                <td class="text-center"><?php echo $inventario['marca']; ?></td>
                <td class="text-center"><?php echo $inventario['precio']; ?></td>
                <td class="text-center"><?php echo $inventario['stock']; ?></td>
                <td class="text-center"><?php echo $inventario['fecha_entrada']; ?></td>
                <td class="text-center"><?php echo $inventario['categoria']; ?></td>
                <td class="text-center"><?php echo $inventario['razon_social']; ?></td>
            </tr>
                <?php $i++; ?>
            <?php endforeach; ?>
            </tbody>

        </table>
    </div>
</div>
