<?php
$i = 1;
echo $this->headTitle('KARDEX - Codigo: '.$this->kardex[0]['codigo']);
?>
<?php
echo  $this->headLink()->prependStylesheet($this->basePath() . '/js/datatable/datatables.min.css');
echo $this->headScript()
    ->prependFile($this->basePath() . '/js/datatable/datatables.min.js');
?>
<script>
    $(document).ready(function(){
        $('#myTable').DataTable( {
            autoFill: true
        } );
        $('[data-toggle="tooltip"]').tooltip()
    });
</script>
<div style="float: right">
    <a href="<?php echo $this->url('kardex'); ?>id/<?php echo $this->kardex[0]['id_inventario']; ?>">
        <button class="btn btn-default hidden-xs">
            <span class="glyphicon glyphicon-refresh"></span> Actualizar
        </button>
        <button class="btn btn-default visible-xs-inline">
            <span class="glyphicon glyphicon-refresh"></span>
        </button>
    </a>
</div>
<div style="float: right">
    <button class="btn btn-default hidden-xs" data-toggle="modal" data-target="#myModal">
        <span class="glyphicon glyphicon-save"></span> Reporte Excel
    </button>
    <button class="btn btn-default visible-xs-inline" data-toggle="modal" data-target="#myModal">
        <span class="glyphicon glyphicon-save"></span>
    </button>
</div>
<div style="float: right">
    <a href="javascript:history.back()">
        <button class="btn btn-default hidden-xs">
            <span class="glyphicon glyphicon-menu-left"></span> Regresar
        </button>
        <button class="btn btn-default visible-xs-inline">
            <span class="glyphicon glyphicon-menu-left"></span>
        </button>
    </a>
</div>
<h1 class="page-header"><span class="glyphicon glyphicon-align-justify"></span> Kardex  <small>Codigo: <?php echo $this->kardex[1]['codigo']  ?></small></h1>
<div class="panel-info">
    <div class="panel-heading">
        KARDEX
    </div>
    <div class="panel-body table-responsive">
        <table id="myTable" class="table table-bordered">
            <thead>
            <th class="col-md-1 text-center">#</th>
            <th class="col-md-1 text-center">OPERACION</th>
            <th class="text-center">PRODUCTOS</th>
            <th class="text-center">DOCUMENTO</th>
            <th class="text-center">CANTIDAD</th>
            <th class="text-center">FECHA DE ENTRADA</th>
            <th class="text-center">FECHA DE SALIDA</th>
            </thead>
            <tbody>
            <?php foreach ($this->kardex as $kardex) :?>
                <?php if($kardex['tipo_operacion'] == 'Apertura') : ?>
            <tr class="success">
                <td class="text-center"><?php echo $i; ?></td>
                <td class="text-center"><span class="label label-success"><?php echo $kardex['tipo_operacion']; ?></span></td>
                <td class="text-center"><?php echo $kardex['productos']; ?></td>
                <td class="text-center"><a data-original-title="<?php echo $kardex['descripcion']; ?>" href="#" data-toggle="tooltip" data-placement="bottom" title=""><?php echo $kardex['documento']; ?></a></td>
                <td class="text-center"><?php echo $kardex['cantidad']; ?></td>
                <td class="text-center"><?php echo $kardex['fecha_entrada']; ?></td>
                <td class="text-center"><?php echo $kardex['fecha_salida']; ?></td>
            </tr>
           <?php else: ?>
                    <tr>
                        <td class="text-center"><?php echo $i; ?></td>
                        <?php if($kardex['tipo_operacion'] == 'Entrada'):?>
                        <td class="text-center"><span class="label label-info"><?php echo $kardex['tipo_operacion']; ?></span></td>
                        <?php else: ?>
                        <td class="text-center"><span class="label label-danger"><?php echo $kardex['tipo_operacion']; ?></span></td>
                        <?php endif; ?>
                        <td class="text-center"><?php echo $kardex['productos']; ?></td>
                        <td class="text-center"><a data-original-title="<?php echo $kardex['descripcion']; ?>" href="#" data-toggle="tooltip" data-placement="bottom" title=""><?php echo $kardex['documento']; ?></a></td>
                        <td class="text-center"><?php echo $kardex['cantidad']; ?></td>
                        <td class="text-center"><?php echo $kardex['fecha_entrada']; ?></td>
                        <td class="text-center"><?php echo $kardex['fecha_salida']; ?></td>
                    </tr>
           <?php endif; ?>
            <?php $i++; ?>
            <?php endforeach; ?>
            </tbody>

        </table>
    </div>
</div>
